# Generated by Django 2.2.12 on 2020-10-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emocioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_contacto',
            name='linkWha',
            field=models.URLField(blank=True, null=True, verbose_name='Numero de whatsapp'),
        ),
        migrations.AlterField(
            model_name='info',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion Web'),
        ),
    ]
