# Generated by Django 2.2.12 on 2020-10-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emocioApp', '0002_auto_20201004_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={},
        ),
    ]
