# Generated by Django 2.2.12 on 2020-10-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emocioApp', '0003_auto_20201004_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Datos inicio'},
        ),
    ]
